// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO
  documents (
    title,
    slug,
    filename,
    mime_type,
    size_bytes,
    storage_path,
    tags
  )
VALUES
  (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::bigint,
    $6::text,
    $7::text[]
  )
RETURNING
  id, title, slug, filename, mime_type, size_bytes, storage_path, created_at, updated_at, tags, deleted_at
`

type CreateDocumentParams struct {
	Title       string
	Slug        string
	Filename    string
	MimeType    string
	SizeBytes   int64
	StoragePath string
	Tags        []string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Title,
		arg.Slug,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StoragePath,
		arg.Tags,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.DeletedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT
  title,
  filename,
  mime_type,
  storage_path,
  size_bytes,
  tags,
  created_at
FROM
  documents
WHERE
  id = $1::uuid
  AND deleted_at IS NULL
`

type GetDocumentRow struct {
	Title       string
	Filename    string
	MimeType    string
	StoragePath string
	SizeBytes   int64
	Tags        []string
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) GetDocument(ctx context.Context, id pgtype.UUID) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.Title,
		&i.Filename,
		&i.MimeType,
		&i.StoragePath,
		&i.SizeBytes,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const listAllDocuments = `-- name: ListAllDocuments :many
SELECT
  id, title, slug, filename, mime_type, size_bytes, storage_path, created_at, updated_at, tags, deleted_at
FROM
  documents
WHERE
  deleted_at IS NULL
ORDER BY
  created_at DESC
LIMIT
  $1
`

func (q *Queries) ListAllDocuments(ctx context.Context, limit pgtype.Int4) ([]Document, error) {
	rows, err := q.db.Query(ctx, listAllDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT
  id, title, slug, filename, mime_type, size_bytes, storage_path, created_at, updated_at, tags, deleted_at
FROM
  documents
WHERE
  (
    (
      title ILIKE '%' || $1::text || '%'
    )
    OR EXISTS (
      SELECT
        1
      FROM
        unnest(tags) AS t
      WHERE
        t ILIKE '%' || $1::text || '%'
    )
  )
  AND deleted_at IS NULL
ORDER BY
  created_at DESC
LIMIT
  $2
`

type ListDocumentsParams struct {
	SearchTerm string
	Limit      pgtype.Int4
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.SearchTerm, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
