// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID          pgtype.UUID
	Title       string
	Slug        string
	Filename    string
	MimeType    string
	SizeBytes   int32
	StoragePath string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
