// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID          pgtype.UUID
	Title       string
	Slug        string
	Filename    string
	MimeType    string
	SizeBytes   int64
	StoragePath string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Tags        []string
}
