depends_on:
  - lint
  - test
  - security

when:
  - event: push
    branch: main

steps:
  - name: build-and-push
    image: docker:27-cli
    environment:
      REGISTRY_USER:
        from_secret: REGISTRY_USER
      REGISTRY_PASS:
        from_secret: REGISTRY_PASS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "$REGISTRY_PASS" | docker login http://192.168.76.202:3000 -u "$REGISTRY_USER" --password-stdin
      - SHORT_SHA=$(echo "$CI_COMMIT_SHA" | cut -c1-8)
      - docker build -t 192.168.76.202:3000/pedro/recall-server:latest -t 192.168.76.202:3000/pedro/recall-server:$SHORT_SHA .
      - docker push 192.168.76.202:3000/pedro/recall-server:latest
      - docker push 192.168.76.202:3000/pedro/recall-server:$SHORT_SHA
