depends_on:
  - build

when:
  - event: push
    branch: main

steps:
  - name: goose-up
    image: ghcr.io/kukymbr/goose-docker:3.27.1 
    environment:
      GOOSE_URL:
        from_secret: GOOSE_URL
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: ./internal/storage/schemas
      
    commands:
      - goose up

